config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

app_name = 'config'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='threads:category_list', permanent=True)),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'), name='accounts'),
    path('threads/', include('threads.urls'), name='threads')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

threads/urls.py
from django.urls import path
from threads.views import (
    CategoryListView,
    ThreadListView,
    ThreadDetailView,
    ThreadCreateView,
    ReportCreateView,
    ReportListView,
    UpvoteView,
    DeleteView,
    LockView,
    ThreadEditView,
    ReplyEditView,
    ReportUpdateStatusView,
    TagCreateView
)

app_name = 'threads'
urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<slug:slug>/<str:order_by>/', ThreadListView.as_view(), name='thread_list'),
    path('view/<int:pk>/<str:order_by>/', ThreadDetailView.as_view(), name='thread_detail'),
    path('create/<int:pk>/', ThreadCreateView.as_view(), name='thread_create'),
    path('create/tags/', TagCreateView.as_view(), name='tag_create'),
    path('edit/<int:pk>/thread/', ThreadEditView.as_view(), name='thread_edit'),
    path('edit/<int:pk>/reply/', ReplyEditView.as_view(), name='reply_edit'),
    path('reports/create/<int:pk>/<str:type>/', ReportCreateView.as_view(), name='report_create'),
    path('reports/', ReportListView.as_view(), name='report_list'),
    path('reports/update/<int:pk>/', ReportUpdateStatusView.as_view(), name='report_update'),
    path('upvote/<int:pk>/<str:type>/', UpvoteView.as_view(), name='upvote'),
    path('delete/<int:pk>/<str:type>/', DeleteView.as_view(), name='delete'),
    path('lock/<int:pk>/', LockView.as_view(), name='lock')
]

threads/models.py
import bleach
import markdown
from django.db import models, transaction, IntegrityError
from django.urls import reverse_lazy
from django.conf import settings
from django.core import validators
from django.utils import text
from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from threads.utils import queue_mail, queue_mass_mail

# Create your models here.

class Category(models.Model):

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(verbose_name='name', max_length=255, unique=True)
    slug = models.SlugField(verbose_name='slug', unique=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        update_fields = kwargs.get('update_fields')
        if is_new or (update_fields is None) or (update_fields and 'name' in update_fields):
            slug = text.slugify(self.name)
            count = 0
            self.slug = slug
            while True:
                try:
                    with transaction.atomic():
                        super().save(*args, **kwargs)
                    return
                except IntegrityError:
                    count += 1
                    self.slug = f'{slug}-{count}'
        super().save(*args, **kwargs)
        
    def __str__(self) -> str:
        return f'Category Name: {self.name}'


class Tag(models.Model):
    
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    hex_validator = validators.RegexValidator(
        regex=r'^#[A-Fa-f0-9]{6}$',
        message='Enter a valid hex color code'
    )

    name = models.CharField(verbose_name='name', max_length=255, unique=True)
    color = models.CharField(verbose_name='color', max_length=7, validators=[hex_validator])

    def __str__(self) -> str:
        return str(self.name)


class Post(models.Model):

    class Meta:
        abstract = True

    upvotes = models.ManyToManyField(verbose_name='upvotes', to=settings.AUTH_USER_MODEL, blank=True, related_name='upvoted_%(class)s')
    upvote_count = models.PositiveIntegerField(verbose_name='upvote count', default=0)
    raw_content = models.TextField(verbose_name='raw_content')
    author = models.ForeignKey(verbose_name='author', to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='%(class)s')
    created_at = models.DateTimeField(verbose_name='created at', auto_now_add=True)
    is_deleted = models.BooleanField(verbose_name='is deleted', default=False)

    @property
    def content(self) -> str:
        if self.is_deleted:
            return '_[This content has been removed]_'
        else:
            markdown_content = markdown.markdown(text=self.raw_content, extensions=['extra', 'nl2br', 'codehilite'])
            allowed_tags = ['p', 'br', 'strong', 'em', 'u', 'blockquote', 'h1', 'h2', 'h3', 'ul', 'ol', 'li', 'code', 'pre', 'table', 'thead', 'tbody', 'tr', 'th', 'td', 'a']
            allowed_attrs = {'a': ['href', 'title', 'target'], '*': ['class']}
            allowed_protocols = ['http', 'https', 'mailto']
            return bleach.clean(text=markdown_content, tags=allowed_tags, attributes=allowed_attrs, protocols=allowed_protocols)

    @transaction.atomic
    def update_upvotes(self, user) -> None:
        obj = self.__class__.objects.select_for_update().get(pk=self.pk)
        if obj.upvotes.filter(id=user.id).exists():
            obj.upvotes.remove(user)
            amount = -1
        else:
            obj.upvotes.add(user)
            amount = 1
        obj.upvote_count = models.F('upvote_count') + amount
        obj.save(update_fields=['upvote_count'])

    @transaction.atomic
    def soft_delete(self):
        obj = self.__class__.objects.select_for_update().get(pk=self.pk)
        if not obj.is_deleted:
            obj.is_deleted = True
            obj.save(update_fields=['is_deleted'])

    def _get_mentioned(self):
        User = get_user_model()
        excluded = '.,!?;:()[]{}\"\'/\\<>*&^%$#='
        words = {i.strip(excluded) for i in self.raw_content.split()}
        mentions = {i.lstrip('@') for i in words if i.startswith('@')}
        mentioned_users = User.objects.filter(username__in=mentions).exclude(pk=self.author.pk)
        return mentioned_users
        
    def save(self, *args, **kwargs) -> None:
        is_new = self.pk is None
        update_fields = kwargs.get('update_fields')
        super().save(*args, **kwargs)
        if is_new or (update_fields is None) or (update_fields and 'raw_content' in update_fields):
            if isinstance(self, Thread):
                pk = self.pk
            else:
                pk = self.thread.pk # type: ignore
            subject = f'You have been mentioned in a {self.__class__.__name__}'
            link = f'https://forumdeck.sreyash.tech{str(reverse_lazy('threads:thread_detail', kwargs={'pk': pk, 'order_by': '-created_at'}))}'
            body=f'Mentioned By: {self.author}\nMentioned At: {self.created_at}\nClick this link to view: {link}'
            messages = []
            for user in self._get_mentioned():
                message = (
                    subject,
                    body,
                    settings.DEFAULT_FROM_EMAIL,
                    [user.email]
                )
                messages.append(message)
            queue_mass_mail(messages=tuple(messages))


class Trigram(models.Model):
    
    class Meta:
        verbose_name = 'Trigram'
        verbose_name_plural = 'Trigrams'
    
    value = models.CharField(verbose_name='value', max_length=3, db_index=True, unique=True)


class Thread(Post):

    class Meta(Post.Meta):
        abstract = False
        verbose_name = 'Thread'
        verbose_name_plural = 'Threads'
        ordering = ['-created_at']
    
    category = models.ForeignKey(verbose_name='category', to='threads.Category', on_delete=models.CASCADE, related_name='threads')
    title = models.CharField(verbose_name='title', max_length=255)
    trigrams = models.ManyToManyField(verbose_name='trigrams', to='threads.Trigram', blank=True, related_name='threads')
    tagged_courses = models.ManyToManyField(verbose_name='tagged courses', to='courses.Course', blank=True, related_name='tagged')
    tagged_documents = models.ManyToManyField(verbose_name='tagged documents', to='courses.Resource', blank=True, related_name='tagged')
    tags = models.ManyToManyField(verbose_name='tags', to='threads.Tag', blank=True, related_name='tagged')
    is_locked = models.BooleanField(verbose_name='is locked', default=False)
    reply_count = models.PositiveIntegerField(verbose_name='reply_count', default=0)

    @classmethod
    def fuzzy_search(cls, prompt: str):
        prompt = f'  {prompt.lower()}  '
        prompt_values = [prompt[i:i+3] for i in range(len(prompt) - 2)]
        return cls.objects.filter(
            trigrams__value__in=prompt_values
        ).annotate(
            score=models.Count('trigrams')
        ).filter(
            score__gte=2
        ).order_by(
            '-score'
        )

    @transaction.atomic
    def update_lock(self):
        obj = self.__class__.objects.select_for_update().get(pk=self.pk)
        if obj.is_locked:
            obj.is_locked = False
        else:
            obj.is_locked = True
        obj.save(update_fields=['is_locked'])

    @transaction.atomic
    def _save_trigrams(self) -> None:
        obj = self.__class__.objects.select_for_update().get(pk=self.pk)
        title = f'  {obj.title.lower()}  '
        values: set[str] = set([title[i:i+3] for i in range(len(title) - 2)])
        Trigram.objects.bulk_create([Trigram(value=value) for value in values], ignore_conflicts=True)
        trigrams = Trigram.objects.filter(value__in=values)
        obj.trigrams.set(trigrams)

    def save(self, *args, **kwargs) -> None:
        is_new = self.pk is None
        super().save(*args, **kwargs)
        update_fields = kwargs.get('update_fields')
        if is_new or (update_fields is None) or (update_fields and 'title' in update_fields):
            self._save_trigrams()
    
    def __str__(self) -> str:
        return f'Thread Title: {self.title}\nAuthor: {self.author}\nContent: {self.content}'


class Reply(Post):

    class Meta(Post.Meta):
        abstract = False
        verbose_name = 'Reply'
        verbose_name_plural = 'Replies'
        ordering = ['thread', '-created_at']

    thread = models.ForeignKey(verbose_name='thread', to='threads.Thread', on_delete=models.CASCADE, related_name='replies')

    @transaction.atomic
    def soft_delete(self) -> None:
        thread = Thread.objects.select_for_update().get(pk=self.thread.pk)
        obj = self.__class__.objects.select_for_update().get(pk=self.pk)
        if not obj.is_deleted:
            obj.is_deleted = True
            thread.reply_count=models.F('reply_count') - 1
            obj.save(update_fields=['is_deleted'])
            thread.save(update_fields=['reply_count'])

    def save(self, *args, **kwargs) -> None:
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            Thread.objects.filter(pk=self.thread.pk).update(reply_count=models.F('reply_count') + 1)
            subject = f'Your thread has gotten replies!'
            link = f'https://forumdeck.sreyash.tech{str(reverse_lazy('threads:thread_detail', kwargs={'pk': self.thread.pk, 'order_by': '-created_at'}))}'
            body = f'{self.author} has replied to your thread on {self.thread.category} at {self.created_at}\nView your thread: {link}'
            queue_mail(
                to=self.thread.author.email,
                subject=subject,
                body=body
            )

    def __str__(self) -> str:
        return f'Reply to: {self.thread}\nAuthor: {self.author}\nContent: {self.content}'


class Report(models.Model):

    class Meta:
        verbose_name = 'Report'
        verbose_name_plural = 'Reports'

threads/forms.py
from typing import Any
from datetime import timedelta
from django import forms
from django.utils import timezone
from django.core.validators import RegexValidator
from threads.models import Report, Reply, Thread

class ReportCreateForm(forms.ModelForm):
    
    class Meta:
        model = Report
        fields = ['reason']

    def __init__(self, *args, **kwargs) -> None:
        self.reporter = kwargs.pop('reporter')
        super().__init__(*args, **kwargs)

    def clean(self) -> dict[str, Any]:
        cleaned_data = super().clean()
        time_delay = timezone.now() - timedelta(minutes=5)
        report_count = Report.objects.filter(reporter=self.reporter, created_at__gte=time_delay).count()
        if report_count >= 3:
            raise forms.ValidationError('You are reporting too fast!')
        return cleaned_data


class ThreadCreateForm(forms.ModelForm):

    class Meta:
        model = Thread
        fields = ['title', 'raw_content', 'tags', 'tagged_courses', 'tagged_documents']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'raw_content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4
            })
        }

    def __init__(self, *args, **kwargs) -> None:
        self.author = kwargs.pop('author')
        super().__init__(*args, **kwargs)

    def clean(self) -> dict[str, Any]:
        cleaned_data = super().clean()
        time_delay = timezone.now() - timedelta(minutes=2)
        count = Thread.objects.filter(author=self.author, created_at__gte=time_delay).count()
        if count >= 2:
            raise forms.ValidationError('You are creating threads too fast!')
        return cleaned_data


class ReplyCreateForm(forms.ModelForm):
    
    class Meta:
        model = Reply
        fields = ['raw_content']
        widgets = {
            'raw_content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4
            })
        }

    def __init__(self, *args, **kwargs) -> None:
        self.author = kwargs.pop('author')
        super().__init__(*args, **kwargs)

    def clean(self) -> dict[str, Any]:
        cleaned_data = super().clean()
        time_delay = timezone.now() - timedelta(minutes=2)
        count = Reply.objects.filter(author=self.author, created_at__gte=time_delay).count()
        if count >= 2:
            raise forms.ValidationError('You are creating replies too fast!')
        return cleaned_data


class TagCreateForm(forms.Form):
    tag_validator = RegexValidator(
        regex=r'^[a-zA-Z0-9 ]+$',
        message='Enter the tags separated by whitespaces, they cannot include special characters!'
    )
    tags = forms.CharField(
        required=True, 
        validators=[tag_validator], 
        strip=True,
        widget=forms.widgets.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'e.g. physics chemistry maths thermodynamics'
        })
    )

templates/threads/category_list.html
{% extends 'base.html' %}

{% block content %}
<div class="content-box text-center mb-5">
    <h1 class="fw-bold display-6 mb-2 text-dark">Explore Topics</h1>
    <p class="text-secondary mb-0">Select a category to join the conversation.</p>
</div>

<div class="row g-4">
    {% for category in categories %}
    <div class="col-md-6">
        <a href="{% url 'threads:thread_list' slug=category.slug order_by='-created_at' %}" class="text-decoration-none">
            <div class="category-card h-100 p-4 text-center transition-lift border-0">
                <div class="bg-light rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style="width: 50px; height: 50px;">
                    <span class="fs-4 fw-bold text-dark">{{ category.name|slice:":1" }}</span>
                </div>
                <h5 class="card-title fw-bold text-dark mb-2">{{ category.name }}</h5>
                {% if category.description %}
                <p class="text-muted small mb-0">{{ category.description }}</p>
                {% else %}
                <p class="text-muted small mb-0">Join the discussion</p>
                {% endif %}
            </div>
        </a>
    </div>
    {% endfor %}
</div>

<style>
    .transition-lift { transition: transform 0.2s; }
    .transition-lift:hover { transform: translateY(-3px); box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
</style>
{% endblock %}

templates/threads/report_list.html
{% extends 'base.html' %}

{% block content %}

<div class="content-box mb-5">
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
        <div>
            <h1 class="fw-bold h3 text-dark mb-1">Moderation Queue</h1>
            <p class="text-secondary mb-0">Review user reports and take action.</p>
        </div>
        <div class="d-flex gap-2">
            <span class="badge bg-danger rounded-pill px-3 py-2 border border-danger bg-opacity-10 text-danger">
                {% if page_obj %}
                    {{ page_obj.paginator.count }} Total
                {% else %}
                    {{ reports|length|default:"0" }} Total
                {% endif %}
            </span>
        </div>
    </div>
</div>

<div class="d-flex flex-column gap-3">
    {# Loop directly over 'reports' since we saw it in your error log #}
    {% for report in reports %}
    
    <div class="report-card p-0 overflow-hidden {% if report.status == 'RESOLVED' %}opacity-75 bg-light{% endif %}" style="transition: all 0.2s;">
        
        <div class="p-3 border-bottom d-flex justify-content-between align-items-center flex-wrap gap-2 {% if report.status == 'RESOLVED' %}bg-secondary bg-opacity-10{% else %}bg-light{% endif %}">
            <span class="small text-muted">
                <i class="bi bi-flag-fill {% if report.status == 'RESOLVED' %}text-muted{% else %}text-danger{% endif %} me-2"></i>
                
                <strong>{{ report.reporter.first_name|default:report.reporter.username }}</strong> 
                <span class="text-muted fw-normal small">(@{{ report.reporter.username }})</span>
                
                reported 
                {% if report.thread %}a Thread{% else %}a Reply{% endif %}
                &bull; {{ report.created_at|timesince }} ago
            </span>
            
            {% if report.status == 'PENDING' %}
                <span class="badge bg-warning text-dark border shadow-sm">PENDING</span>
            {% else %}
                <span class="badge bg-success text-white border shadow-sm">RESOLVED</span>
            {% endif %}
        </div>

        <div class="p-4">
            <div class="mb-3">
                <label class="sidebar-label text-danger mb-1">Reason</label>
                <div class="text-dark fw-medium">{{ report.reason }}</div>
            </div>

            <!-- SAFE CONTENT ACCESS -->
            <div class="p-3 bg-white rounded-3 mb-4 border shadow-sm">
                <label class="sidebar-label mb-2">Offending Content</label>
                <div class="text-secondary fst-italic text-break">
                    
                    {% if report.thread %}
                        <strong class="d-block mb-1">{{ report.thread.title }}</strong>
                        <div>"{{ report.thread.content|striptags|truncatechars:200 }}"</div>
                        
                    {% elif report.reply %}
                        {% if report.reply.thread %}
                            <strong class="d-block mb-1">Reply in: {{ report.reply.thread.title }}</strong>
                        {% else %}
                            <strong class="d-block mb-1 text-danger">Reply in: [Deleted Thread]</strong>
                        {% endif %}
                        
                        <div>"{{ report.reply.content|striptags|truncatechars:200 }}"</div>
                        
                    {% else %}
                        <span class="text-muted">(Content unavailable / deleted)</span>
                    {% endif %}
                    
                </div>
                
                <div class="mt-2 text-end border-top pt-2">
                    {% if report.thread %}
                        <a href="{% url 'threads:thread_detail' pk=report.thread.pk order_by='-created_at' %}" class="small fw-bold text-decoration-none" target="_blank">
                            View Thread <i class="bi bi-box-arrow-up-right ms-1"></i>
                        </a>
                    {% elif report.reply and report.reply.thread %}
                        <a href="{% url 'threads:thread_detail' pk=report.reply.thread.pk order_by='-created_at' %}" class="small fw-bold text-decoration-none" target="_blank">
                            View Context <i class="bi bi-box-arrow-up-right ms-1"></i>
                        </a>
                    {% endif %}
                </div>
            </div>

            <div class="d-flex gap-2 flex-wrap">
                <form action="{% url 'threads:report_update' pk=report.pk %}?next={{ request.get_full_path }}" method="post" class="flex-grow-1">
                    {% csrf_token %}
                    {% if report.status == 'PENDING' %}
                        <button class="btn btn-success w-100 fw-bold text-white shadow-sm" style="border-radius: var(--radius-sharp);">
                            <i class="bi bi-check-circle-fill me-2"></i> Mark Resolved
                        </button>
                    {% else %}
                        <button class="btn btn-white border w-100 fw-bold text-muted shadow-sm" style="border-radius: var(--radius-sharp);">
                            <i class="bi bi-arrow-counterclockwise me-2"></i> Re-open Report
                        </button>
                    {% endif %}
                </form>

                {% if report.status == 'PENDING' %}
                    {% if report.thread %}
                    <form action="{% url 'threads:delete' pk=report.thread.pk type='thread' %}?next={{ request.get_full_path }}" method="post" class="flex-grow-1">
                        {% csrf_token %}
                        <button class="btn btn-danger w-100 fw-bold shadow-sm" style="border-radius: var(--radius-sharp);" onclick="return confirm('Delete this thread permanently?')">
                            <i class="bi bi-trash me-1"></i> Delete Content
                        </button>
                    </form>
                    {% elif report.reply %}
                    <form action="{% url 'threads:delete' pk=report.reply.pk type='reply' %}?next={{ request.get_full_path }}" method="post" class="flex-grow-1">
                        {% csrf_token %}
                        <button class="btn btn-danger w-100 fw-bold shadow-sm" style="border-radius: var(--radius-sharp);" onclick="return confirm('Delete this reply permanently?')">
                            <i class="bi bi-trash me-1"></i> Delete Content
                        </button>
                    </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    {% empty %}
    <div class="content-box text-center py-5">
        <div class="bg-success bg-opacity-10 text-success rounded-circle d-inline-flex p-4 mb-3">
            <i class="bi bi-shield-check display-4"></i>
        </div>
        <h3 class="fw-bold text-dark">All Clear</h3>
        <p class="text-muted mb-0">No reports found.</p>
    </div>
    {% endfor %}

    <!-- PAGINATION -->
    {% if is_paginated %}
    <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            {% endif %}

            <li class="page-item disabled">
                <span class="page-link text-dark">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

{% block right_sidebar %}
<div class="mb-4">
    <label class="sidebar-label">Legend</label>
    <div class="widget-box p-3">
        <div class="d-flex align-items-center gap-2 mb-2">
            <span class="badge bg-warning text-dark border">PENDING</span>
            <span class="text-muted small">Requires attention. Content is live.</span>
        </div>
        <div class="d-flex align-items-center gap-2">
            <span class="badge bg-success text-white border">RESOLVED</span>
            <span class="text-muted small">Handled or dismissed.</span>
        </div>
    </div>
</div>
{% endblock %}

templates/threads/thread_create.html
{% extends 'base.html' %}

{% block content %}
<div class="mb-4">
    <a href="{% url 'threads:thread_list' slug=category.slug order_by='-created_at' %}" class="btn btn-white border shadow-sm px-3 py-1 text-muted fw-bold small rounded-pill">
        <i class="bi bi-arrow-left me-1"></i> Cancel
    </a>
</div>

<div class="content-box p-5 border-0 shadow-sm">
    <div class="mb-4 pb-4 border-bottom">
        <h1 class="fw-bold h3 text-dark mb-1">Start a Discussion</h1>
        <p class="text-secondary mb-0">Share your thoughts in <strong>{{ category.name }}</strong>.</p>
    </div>

    <form method="post">
        {% csrf_token %}

        {% if form.errors %}
            <div class="mb-4">
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <div class="alert alert-danger border-0 py-2 px-3 small">{{ field|title }}: {{ error }}</div>
                    {% endfor %}
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-group mb-4">
            <label class="sidebar-label text-dark mb-2">Title</label>
            {{ form.title }}
        </div>

        <div class="form-group mb-4">
            <label class="sidebar-label text-dark mb-2">Content</label>
            {{ form.raw_content }}
            <div class="form-text mt-1">Markdown is supported.</div>
        </div>

        <div class="row mb-4">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="sidebar-label text-dark mb-2">Related Courses</label>
                    {{ form.tagged_courses }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="sidebar-label text-dark mb-2">Related Documents</label>
                    {{ form.tagged_documents }}
                </div>
            </div>
        </div>

        <div class="form-group mb-5">
            <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-2">
                <label class="sidebar-label text-dark mb-0">Topics</label>
                <a href="{% url 'threads:tag_create' %}?next={{ request.path }}" class="small fw-bold text-decoration-none text-primary">
                    <i class="bi bi-plus-circle me-1"></i> Create New Topic
                </a>
            </div>
            {{ form.tags }}
            <div class="form-text">Select relevant topics for this discussion.</div>
        </div>

        <div class="d-flex justify-content-end flex-wrap gap-2">
            <button type="submit" class="btn btn-dark fw-bold px-5 py-2">Post Discussion</button>
        </div>
    </form>
</div>

<style>
    .ts-control {
        border: 1px solid #dee2e6;
        padding: 12px;
        border-radius: 8px;
        box-shadow: none;
        background-color: #FAFAFA;
    }
    .ts-control.focus {
        border-color: #000;
        box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.05);
    }
    .ts-dropdown {
        border-radius: 8px;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        border: 1px solid #f3f4f6;
    }
    textarea { min-height: 200px; }
    
    input:focus, textarea:focus {
        background-color: #fff;
        border-color: #000;
        outline: 0;
        box-shadow: 0 0 0 3px rgba(0, 0, 0, 0.05);
    }
</style>

<link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.bootstrap5.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/js/tom-select.complete.min.js"></script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // 1. Tags Configuration (Creation Disabled Here)
        if(document.getElementById('id_tags')) {
            new TomSelect("#id_tags", {
                plugins: ['remove_button'],
                maxItems: 5,
                placeholder: "Select topics...",
                create: false, // Force user to use the 'Create New Topic' link
                render: {
                    item: function(data, escape) {
                        return '<div>' + escape(data.text) + '</div>';
                    }
                }
            });
        }
        
        // 2. Courses Configuration
        if(document.getElementById('id_tagged_courses')) {
            new TomSelect("#id_tagged_courses", {
                plugins: ['remove_button'],
                maxItems: 5,
                placeholder: "Search for courses...",
                create: false 
            });
        }
        
        // 3. Documents Configuration
        if(document.getElementById('id_tagged_documents')) {
            new TomSelect("#id_tagged_documents", {
                plugins: ['remove_button'],
                maxItems: 5,
                placeholder: "Search for documents...",
                create: false 
            });
        }
    });
</script>
{% endblock %}

{% block right_sidebar %}
<div class="mb-4">
    <label class="sidebar-label">Guidelines</label>
    <div class="widget-box p-4">
        <ul class="list-unstyled mb-0 text-muted small d-flex flex-column gap-3">
            <li><strong>1. Be Respectful</strong><br>Treat others with kindness.</li>
            <li><strong>2. Stay on Topic</strong><br>Keep discussion relevant.</li>
            <li><strong>3. No Spam</strong><br>Avoid excessive self-promotion.</li>
        </ul>
    </div>
</div>
{% endblock %}